name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        type: choice 
        options:
        - info
        - warning
        - debug
        default: 'warning'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      matrix:
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    name: "run matrix"
    strategy:
      max-parallel: 2
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      
      - run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
